apiVersion: v1
kind: Service
metadata:
  labels:
    name: managed-node-metadata-operator
  name: managed-node-metadata-operator-metrics-service
  namespace: openshift-managed-node-metadata-operator
  annotations:
    package-operator.run/phase: deploy
    package-operator.run/collision-protection: IfNoController
spec:
  selector:
    name: managed-node-metadata-operator
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
