apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: managed-node-metadata-operator
  name: managed-node-metadata-operator-metrics-monitor
  namespace: openshift-managed-node-metadata-operator
  annotations:
    package-operator.run/phase: deploy
    package-operator.run/collision-protection: IfNoController
spec:
  endpoints:
  - path: /metrics
    port: metrics
  namespaceSelector:
    any: false
    matchNames:
    - openshift-managed-node-metadata-operator
  selector:
    matchLabels:
      name: managed-node-metadata-operator
