apiVersion: v1
kind: ServiceAccount
metadata:
  name: managed-node-metadata-operator
  namespace: openshift-managed-node-metadata-operator
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
