apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: managed-node-metadata-operator
  name: managed-node-metadata-operator-metrics-monitor
  namespace: openshift-managed-node-metadata-operator
spec:
  endpoints:
    - path: /metrics
      port: metrics
  namespaceSelector:
    any: false
    matchNames:
      - openshift-managed-node-metadata-operator
  selector:
    matchLabels:
      name: managed-node-metadata-operator
